### ISSUE TITLE
Adjust bibtex output for eprints

### ISSUE THREAD

**Issue by aaccomazzi** [adsabs/export_service#33]
Right now we generate bibtex records such as these:
```
@ARTICLE{2018arXiv180303598K,
      author = {{Kurtz}, Michael J. and {Accomazzi}, Alberto and {Henneken}, Edwin A.},
       title = "{Merging the Astrophysics and Planetary Science Information Systems}",
     journal = {ArXiv e-prints},
    keywords = {Astrophysics - Instrumentation and Methods for Astrophysics, Computer
        Science - Digital Libraries, Physics - Physics and Society},
        year = 2018,
       month = Mar,
      eprint = {arXiv:1803.03598},
      adsurl = {https://ui.adsabs.harvard.edu/#abs/2018arXiv180303598K},
     adsnote = {Provided by the SAO/NASA Astrophysics Data System}
}
```
But testing with the latest AASTeX shows that bibtex processing fails to properly create a link to the arXiv record.  We need to modify the export output to be more in line with classic, in particular adding:
`archivePrefix = "arXiv"` and adjusting the eprint field to be: `eprint = {1803.03598}` 

Here is what the final record should look like:
```
@ARTICLE{2018arXiv180303598K,
   author = {{Kurtz}, M.~J. and {Accomazzi}, A. and {Henneken}, E.~A.},
    title = "{Merging the Astrophysics and Planetary Science Information Systems}",
  journal = {ArXiv e-prints},
archivePrefix = "arXiv",
   eprint = {1803.03598},
 primaryClass = "astro-ph.IM",
 keywords = {Astrophysics - Instrumentation and Methods for Astrophysics, Computer Science - Digital Libraries, Physics - Physics and Society},
     year = 2018,
    month = mar,
   adsurl = {https://ui.adsabs.harvard.edu/#abs/2018arXiv180303598K},
  adsnote = {Provided by the SAO/NASA Astrophysics Data System}
```

**Comment by golnazads** [comment]
Fixed. Here is what we shall get now.
@ARTICLE{2018arXiv180303598K,
      author = {{Kurtz}, Michael J. and {Accomazzi}, Alberto and {Henneken}, Edwin A.},
       title = "{Merging the Astrophysics and Planetary Science Information Systems}",
     journal = {ArXiv e-prints},
    keywords = {Astrophysics - Instrumentation and Methods for Astrophysics, Computer
        Science - Digital Libraries, Physics - Physics and Society},
        year = 2018,
       month = Mar,
      eprint = {1803.03598},
      adsurl = {https://ui.adsabs.harvard.edu/#abs/2018arXiv180303598K},
     adsnote = {Provided by the SAO/NASA Astrophysics Data System}
}

**Comment by aaccomazzi** [comment]
The output you have is still missing `archivePrefix` and (less important) `primaryClass`
